name: Web E2E Tests

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Clone do projeto para a máquina
      - uses: actions/checkout@v4

      # Conferir a versão instalada
      - name: Node version
        run: node --version

      - name: Instalando dependências
        run: npm install

      - name: Executando o trabalho final automation-exercise.modules.cy.js
        run: npm run cy:run -- --spec "cypress/e2e/automation-exercise-modules.cy.js"
        # Para o trabalho final, vamos rodar apenas esse arquivo

      - uses: actions/upload-artifact@v4
        # Garante que os artefatos sejam sempre enviados, mesmo se os testes falharem
        if: ${{ !cancelled() }}
        with:
          name: relatorios
          path: |
            cypress/videos
            cypress/screenshots
            cypress/reports   
